### ISSUE TITLE
Unable to install pipenv

### ISSUE THREAD

**Issue by zmazza** [ProgrammingBuddies/programmingbuddies-api#33]
Receiving error pipenv: command not found.

Installed using both pip and pip3.

Able to resolve using sudo -H pip install -U pipenv

**Comment by ghost** [comment]
can you post the full command you run + the resulting error message when installing pipenv?

nvm misread that.

what OS are you using?
Have you checked that the path where pip installs the binaries is on your PATH.

Alternatively you can run it with `python -m pipenv`

**Comment by zmazza** [comment]
Running on Ubuntu 
zmazza@ubuntu:~/Documents/python/programmingbuddies-api$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic


```
zmazza@ubuntu:~/Documents/python/programmingbuddies-api$ sudo pip install pipenvWARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
^CTraceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/zmazza/.local/lib/python2.7/site-packages/pip/__init__.py", line 18, in main
    return _wrapper(args)
  File "/home/zmazza/.local/lib/python2.7/site-packages/pip/_internal/utils/entrypoints.py", line 31, in _wrapper
    return main(args)
  File "/home/zmazza/.local/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/home/zmazza/.local/lib/python2.7/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/zmazza/.local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/home/zmazza/.local/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 19, in <module>
    from pip._internal.network.session import PipSession
  File "/home/zmazza/.local/lib/python2.7/site-packages/pip/_internal/network/session.py", line 26, in <module>
    from pip._internal.network.auth import MultiDomainBasicAuth
  File "/home/zmazza/.local/lib/python2.7/site-packages/pip/_internal/network/auth.py", line 36, in <module>
    import keyring  # noqa
  File "/usr/lib/python2.7/dist-packages/keyring/__init__.py", line 3, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 153, in <module>
    init_backend()
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 66, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/usr/lib/python2.7/dist-packages/keyring/util/__init__.py", line 21, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 196, in get_all_keyring
    exceptions=TypeError))
  File "/usr/lib/python2.7/dist-packages/keyring/util/__init__.py", line 31, in suppress_exceptions
    for callable in callables:
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 188, in is_class_viable
    keyring_cls.priority
  File "/usr/lib/python2.7/dist-packages/keyring/util/properties.py", line 24, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python2.7/dist-packages/keyring/backends/SecretService.py", line 38, in priority
    list(secretstorage.get_all_collections(bus))
  File "/usr/lib/python2.7/dist-packages/secretstorage/collection.py", line 144, in get_all_collections
    service_obj = bus_get_object(bus, SS_PATH)
  File "/usr/lib/python2.7/dist-packages/secretstorage/util.py", line 55, in bus_get_object
    return bus.get_object(name, object_path, introspect=False)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
  File "/usr/lib/python2.7/dist-packages/dbus/exceptions.py", line 45, in __init__
    def __init__(self, *args, **kwargs):
KeyboardInterrupt
```

**Comment by zmazza** [comment]
I've since installed Python 3.7 as well, including pip3.

**Comment by ghost** [comment]
does it work now with python3?

From the error it looks to me like an old version of pip was the problem?

**Comment by zmazza** [comment]
I think I'm running into issues with Ubuntu's base install of python2. I'm going to recreate the virtual machine, remove python2, and set everything back up.

**Comment by ghost** [comment]
python 2 is in ubuntu by default still I think.
At least from experience its not easy to get out.

But if you install python3.7 and then run python3.7 -m pip install pipenv it should usually work

**Comment by zmazza** [comment]
Let me try that.

**Comment by zmazza** [comment]
pipenv install --python python3.7 did the trick. Closing this issue.
